name: Perseus Build

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    env:
      ANDROID_HOME: ${{ runner.tool_cache }}/android-sdk

    steps:
      - uses: actions/checkout@v3
      
      - name: Setup Java JDK
        uses: actions/setup-java@v3.3.0
        with:
          java-version: "17"
          distribution: "adopt"

      - name: Install Android SDK
        uses: android-actions/setup-android@v2
        with:
          api-level: 31
          build-tools: '31.0.0'
          ndk: false

      - name: Verify Build Tools Installation
        run: |
          echo "Checking installed build tools:"
          ls $ANDROID_HOME/build-tools/31.0.0/

      - name: Build Perseus APK
        run: ./patch_perseus.sh

      - name: Grant Execute Permission
        run: chmod +x ./zipalign_sign.sh

      - name: Zipalign and Sign Android release
        run: ./zipalign_sign.sh
                    
      - uses: marvinpinto/action-automatic-releases@latest
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          automatic_release_tag: "latest"
          draft: true
          title: "Perseus Release v${{ env.PERSEUS_VERSION }}"
          files: |
            build/*.apk
